#!/usr/bin/env bash

volume() {
  pactl get-sink-volume @DEFAULT_SINK@ | sed -n 's/front-left:.* \([0-9]*\%\).*/\1/p'
}

#------------------------------------------------------------------------

volume 
