#!/bin/bash
STRGDIR="$HOME/.local/share/bookmarks"
if ! [ -f "$STRGDIR" ]; then 
	mkdir --parent "$STRGDIR" || exit
fi

command -v dmenu >/dev/null 2>&1 || { echo >&2 "dmenu is required."; }
command -v xclip >/dev/null 2>&1 || { echo >&2 "xclip is required."; }
command -v dunst >/dev/null 2>&1 || { echo >&2 "dunst is required."; }
command -v dunstify >/dev/null 2>&1 || { echo >&2 "dunstify is required."; }

if [ -z "$1" ] || [ "$1" = "-s" ]; then
  # Bookmarking
  CHOICE=$( ls "$STRGDIR" | dmenu -l 5 -p "Select or Create File to save to:" )
  # Replace spaces with underscore.
  CHOICE=${CHOICE// /_}

  if [ "$CHOICE" = 0 ]; then
				dunstify -a Bookmark "Bookmark canceled."
				exit 0
  fi
  touch "$STRGDIR/$CHOICE"
  # Get highlighted text (Primary register)
  CNTNT=$(xclip -o)
  if [ -z "$CNTNT" ]; then 
    dunstify -a Bookmark "Bookmark canceled, no content selected"
    exit 0
  fi

  # Existing bookmarks
  
  BKMKS=$(awk -F: '{print $1 " " "[" $2 "]"}' "$STRGDIR/$CHOICE" )
  # User-Selected name of bookmark
  NAME=$(echo "$BKMKS" | dmenu -l 5 -p "Name of bookmark:")

  if [ "$NAME" = 0 ] || [ -z "$NAME" ]; then
				dunstify -a Bookmark "Bookmark canceled. no name provided."
				exit 0
  fi

	#Create the file if it doenst exist
	if ! [ -f "$STRGDIR/$CHOICE" ]; then
		echo "$NAME:$CNTNT" >> "$STRGDIR/$CHOICE"
	else 
	# Check to see if the name specified is a bookmark
		case $NAME in 
			*$BKMRKS*)

      OTHER=$(  )
      echo "$OTHER"
			NAMECNT=$(dmenu -p "$NAME already exists. Replace (Y/n)")
			#Get old data from bookmark and put it on clipboard
			awk '/'"$NAME"'\:/ {print}' | xclip -selection clipboard

			# IF Y selected then overwrite it w/ sed
			if ! [ "$NAMECNT" = "y" ] && ! [ "$NAMECNT" = "Y" ]; then
				dunstify -a Bookmark "Bookmark canceled."
				exit 0
			fi

			#Replace old entry
			sed -i 's/&'"$NAME"'\:.*/'"$CNTNT"'/' "$STRGDIR/$CHOICE"
				;;
			*)
			echo "$NAME:$CNTNT" >> "$STRGDIR/$CHOICE"
				;;
		esac
	fi
	dunstify -a Bookmark "Bookmark $NAME Saved to $STRGDIR/$SELECTION"

#If bookmark -r then we are retrieving from the file
elif [ "$1" = "-r" ]; then
	#List of files that we use to store the things
	LOCS=$(ls "$STRGDIR")
	SELECTION=$(echo "$LOCS" | dmenu -l 5 -p "Select File for Bookmark: ")
	LOCS=${LOCS//$'\n'/ }
	
	dunstify -a Bookmark "$LOCS\n$SELECTION"
	case $SELECTION in
		*$LOCS*)
		BKMRKS=$( awk -F: '{print $1}' "$STRGDIR/$SELECTION")
		NAME=$(echo "$BKMRKS" | dmenu -l 5 -p "Name of Bookmark:")
		sed 's/^'"$NAME"'://' | xclip -selection clipboard
		if [ -z "$CONTENT" ]; then
			dunstify -a Bookmark "Bookmark $NAME not found in $STRGDIR/$SELECTION"
			exit 0
		fi
			;;
		*)
		dunstify -a Bookmark "No such file found."
		exit 0
			;;
	esac
	
	dunstify -a Bookmark "Bookmark placed on clipboard"

fi

