#!/bin/sh

# User Selects isntallation drive
echo -ne "Hi there, welcome to the install script for Arch Linux.\n\
    This script should in theory provide you a fully working install.\n\
    \\n
    \
    Lets get started.\n"
pause

echo -ne "Not all drives will be listed, only disks will be shown\n\
    Only those that are the actual disk, and 
    Please pick your desired install drive\n\
    You only need to specify the end name, EX \"nvme0n1\"\n\

    "
# Store output of drives for parsing
DRIVES=$(lsblk --list --path --noheadings)

# Print only the drives for the user to select from.
$(echo $DRIVES | awk '{print $1}')

# Store to $INSTALLDRIVE
read -ne INSTALLDRIVE

echo -ne "Please make sure that /dev/`$INSTALLDRIVE` not being used.\n\
    Continue (y/N)"

# user input should be (y, n, N, Y)
while 
    read -ne INPUT
do ! [[ "${INPUT,,}" = "y" ]] || ! [[ "${INPUT,,}" = "n" ]] && echo "Please enter only 'y' or 'n'\n"; done

# Update the deivce name 
INSTALLDRIVE="/dev/`$INSTALLDRIVE`"

# Make sure that the device actually exists and is unmount and ready
SELECTEDDRIVE=$(echo "$DRIVES" | grep "$INPUT")
